### ISSUE TITLE
#5 Build fails because the package-lock.json has been removed but is still present in the dockerfile instructions

### ISSUE THREAD

**Issue by yanntoque** [HugoDF/express-postgres-starter#5]
When firing up ```docker-compose up``` the build fails : 

![Error_package-lock_json-Missing](https://user-images.githubusercontent.com/14300737/65838798-2534bc00-e307-11e9-9429-742d7962fdd7.png)

Indeed the *package-lock.json* file has been removed from the application, but is still present in the **dockerfile** ```COPY``` instruction: 

![dockerfile_wrong](https://user-images.githubusercontent.com/14300737/65838868-d176a280-e307-11e9-8d28-20aff8b021cc.png)

**Comment by HugoDF** [comment]
Thanks for the PR
